version: '3.7'

networks:
  default:
    name: bank-network

services:
  fake-bank-backend:
    container_name: fake-bank-backend
    image: 'fake-bank-backend:latest'
    environment:
      SPRING_PROFILES_ACTIVE: default
    ports:
      - '8080:8080'
    depends_on:
      - fake-bank-backend-database

  fake-bank-backend-database:
    container_name: fake-bank-backend-database
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: fake-bank-backend
      POSTGRES_PASSWORD: backendPassword
    ports:
      - '5432:5432'