version: '3.7'

services:
  fake-bank-backend:
    container_name: fake-bank-backend
    image: 'fake-bank-backend:latest'
    environment:
      SPRING_PROFILES_ACTIVE: local
    network_mode: 'host'
    depends_on:
      - fake-bank-backend-database

  fake-bank-backend-database:
    container_name: fake-bank-backend-database
    image: 'postgres:12.2-alpine'
    environment:
      POSTGRES_USER: fake-bank-backend
      POSTGRES_PASSWORD: backendPassword
    network_mode: 'host'
