version: '3.7'

services:
  fake-bank-backend:
    container_name: fake-bank-backend
    image: 'fake-bank-backend:latest'
    ports:
        - '8080:8080'
    environment:
      SPRING_PROFILES_ACTIVE: default
    depends_on:
      - fake-bank-backend-database

  fake-bank-backend-database:
    container_name: fake-bank-backend-database
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: fake-bank-backend
      POSTGRES_PASSWORD: backendPassword
    ports:
      - '5432:5432'