version: '3.7'

services:
  sonarqube-database:
    container_name: sonarqube-database
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    ports:
      - '5432:5432'

  sonarqube:
    container_name: sonarqube
    image: 'sonarqube:7.9.1-community'
    environment:
      sonar.jdbc.url: jdbc:postgresql://sonarqube-database:5432/sonar
    ports:
      - '9000:9000'
    depends_on:
      - sonarqube-database

  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.14.0'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'