version: '3.7'

services:
  prometheus:
    container_name: prometheus
    image: 'prom/prometheus:v2.14.0'
    volumes:
      - './prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
    network_mode: 'host'

  grafana:
    container_name: grafana
    image: 'grafana/grafana:6.4.4'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - './grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml'
    network_mode: 'host'
    depends_on:
      - prometheus
