version: '3.7'

services:
  keycloak-database:
    container_name: keycloak-database
    image: 'postgres:12.2-alpine'
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - '5432:5432'

  keycloak:
    container_name: keycloak
    image: 'jboss/keycloak:8.0.0'
    environment:
      DB_ADDR: keycloak-database
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json
    volumes:
      - './keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json'
    command:
      - '-Djboss.socket.binding.port-offset=100'
    ports:
      - '8180:8180'
      - '9990:9990'
    depends_on:
      - keycloak-database
