version: '3.7'

services:
  keycloak-database:
    container_name: keycloak-database
    image: 'postgres:12-alpine'
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - '5432:5432'

  keycloak:
    container_name: keycloak
    image: 'jboss/keycloak:8.0.0'
    environment:
      DB_ADDR: keycloak-database
      DB_VENDOR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: keycloak
    volumes:
      - './keycloak/realm-export.json:/opt/jboss/keycloak/imports/realm-export.json'
    command:
      - '-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json'
    ports:
      - '8080:8080'
      - '9990:9990'
    depends_on:
      - keycloak-database
